development:
  adapter: postgresql
  encoding: unicode
  database: d10b5io2s0h1rf
  username: kerwlxrsfylgyk
  password: 27f9a50b52e1bec8db4c7096875e09d63ed3337614e7bd0c451699d279091a35
  host: ec2-52-209-185-5.eu-west-1.compute.amazonaws.com
  port: 5432
  pool: 5


production:
  adapter: postgresql
  prepared_statements: false
  advisory_locks: false


production:
  adapter: postgresql
  statement_limit: 200
