development:
  adapter: postgresql
  encoding: unicode
  database: dfp4rc0ken52t4
  username: dainhksjlqaica
  password: 151cc11bd3b78868d61dbf6476f522257b9cc593a692da408f758d4bc03ff66e
  host: ec2-34-255-225-151.eu-west-1.compute.amazonaws.com
  port: 5432
  pool: 5


production:
  adapter: postgresql
  prepared_statements: false
  advisory_locks: false


production:
  adapter: postgresql
  statement_limit: 200
